name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create .nojekyll in the published artifact to bypass Jekyll (underscored files/dirs)
      - name: Prepare site (ensure .nojekyll and 404.html)
        run: |
          mkdir -p publish
          rsync -av --delete --exclude='.git' ./ publish/
          touch publish/.nojekyll
          if [ ! -f publish/404.html ]; then
            cat > publish/404.html <<'HTML'
<!doctype html>
<meta charset="utf-8">
<title>404 – Seite nicht gefunden</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="icon" href="data:,">
<style>body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;padding:2rem;line-height:1.6}</style>
<h1>404 – Seite nicht gefunden</h1>
<p><a href="/">Zur Startseite</a></p>
HTML
          fi

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./publish

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
